language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-supervisor.gemspec
- gem install sensu-plugins-supervisor-*.gem
before_deploy:
  - bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
