language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-supervisor.gemspec
- gem install sensu-plugins-supervisor-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: RCurZLaMj6zYEhyIxDHZlkcCO5n9tEOrkVDSaedBmqYD1UrPCGnV9SD2N39vR0cb195Vj85NzBKRlej4N9LBBinY+UiNSZhGOlZVF5lesTGGpr5C0fLcGe6hAejnGpnkzyzh8YBVfzRy7nerj6RrzlvvoZKU2bp80q0dg1I50I0=
  gem: sensu-plugins-supervisor
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-supervisor
